### PR TITLE
Fix issue with Gradle 7 (error -> "Configuration with name 'compile' not found.")

### PR DESCRIPTION
**Pull request by HorbachAndrii**
Solution I got from [here](https://github.com/kumparan/react-native-android-inapp-updates/issues/18)

### CODE REVIEW

**Comment by renopp** [comment]
thanks for the contribute @HorbachAndrii 

We will review this PR

**Comment by georgiemathews** [comment]
any updates on this issue?

**Comment by HorbachAndrii** [comment]
just waiting to approve PR

**Comment by addtek** [comment]
When is this PR getting merged?

**Comment by retyui** [comment]
@ferdianr when a master version of pkg will be published in npm?

**Pull request merged**
